### ISSUE TITLE
Licensing on attaching bitstream

### ISSUE THREAD

**Issue by gsallen** [unb-libraries/unb-dspace#37]
We need to develop a system which causes the UNB licence to appear upon attachment of bitstream to pre-populated citation. Currently the licence step only occurs in the complete self-archive process. Since we are trying to bypass that process, we need to find a way to ensure that the files submitted to RiverRun are all licensed for inclusion, and that the depositor is aware of the licence.

**Comment by JacobSanford** [comment]
Mass Closing of Old Issues
