### ISSUE TITLE
Remove metadata generation from ETDMS crosswalk

### ISSUE THREAD

**Issue by jwhitney** [unb-libraries/unb-dspace#44]
(old issue, reposted from Bugzilla)

The ETDMS programmatically generates two metadata elements required by Theses Canada to harvest ETDs from our instance of DSpace.  

1) Theses Canada ID: "TC-UNB-" + the latter half of an item's handle.  E.g., item 1882/12 has TC ID "TC-UNB-12"  This may no longer be necessary, given that TC seems to be implementing a new process for harvesting ETDs: https://etc-hil.basecamphq.com/projects/5866780/posts/44263315/comments

2) URL to full text of item, if it's available.  This is more problematic: the crosswalk searches for a filename ending in ".pdf" & assumes it's the primary bitstream for the item.  

Crosswalks shouldn't generate metadata -- if these are still required by TC (and/or Synergies) appropriate metadata fields should be added to DSpace so the crosswalk can fetch the values from the underlying item, rather than hard-coded, possibly incorrect values.

**Comment by JacobSanford** [comment]
Mass Closing of Old Issues
