### ISSUE TITLE
XMLUI incorrectly resolves requests for CSS files

### ISSUE THREAD

**Issue by jwhitney** [unb-libraries/unb-dspace#53]
The ETCMirage XMLUI theme is set up as a 'sub theme' of Mirage, i.e., ETCMirage refers to Mirage code to style most of the UI,  adding or overriding code only where needed to style RiverRun.  

On etcdev, requests for sub-theme CSS files that differ from base theme CSS files only by theme name resolve incorrectly to the base theme CSS file.  E.g., a request for:

[etcdev.hil.unb.ca:8080] /xmlui/themes/Mirage/lib/css/style.css 

... displays, as expected, the contents of [tomcat]/webapps/xmlui/themes/Mirage/lib/css/style.css.  Unfortunately, so does:

[etcdev.hil.unb.ca:8080] /xmlui/themes/ETCMirage/lib/css/style.css 

This does not seem to be a Tomcat caching issue -- or, at least, not an obvious one.

Other static resources (images, Javascript) do not seem affected.  

This issue does not happen in my VirtualBox setup but it differs from etcdev in OS, JDK, and Tomcat configuration.

**Comment by JacobSanford** [comment]
Mass Closing of Old Issues
