### ISSUE TITLE
alternate version of item published on web

### ISSUE THREAD

**Issue by gsallen** [unb-libraries/unb-dspace#67]
Since DSpace uses dc.identifier.uri for the handle ID, let's indicate other versions available online using the  dc.relation.hasversion field.

This field should appear on the Simple Item View as "Other source" (unless someone has a better idea), and with hyperlinked text.

Items in db with 2 or more records in dc.identifier.uri should have non-handle URI switched to new field.

Item submission forms will need updating so that a URI added on submission is mapped to dc.relation.hasversion. We should probably also change "URI" in dropdown menu under "Identifiers" value-pairs to "URL", which is thew more commonly understood term, and in most cases a more accurate term.

**Comment by JacobSanford** [comment]
Mass Closing of Old Issues
